modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
issueTrackerURL="https://github.com/SaurFort/SaurfortMoreDisc/issues"

[[mods]]
modId="moredisc"
version="${file.jarVersion}"
displayName="SaurFort's MoreDiscs"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="moredisc.png" #optional
credits="My friends who support and help me in my project! I will never forget you!"
authors="Saurfort, Alexion300"
description='''SaurFort's MoreDiscs is all you need for music discs in Minecraft, because this mod implements only remixes and no copyright sounds.'''
[[dependencies.moredisc]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moredisc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
