modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="moredisc"
version="${file.jarVersion}"
displayName="Saurfort's MoreDiscs"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="moredisc.png"
credits="My friends who support and help me in my project! I will never forget you!"
authors="Saurfort, Alexion300"
description='''SaurFort's MoreDiscs is all you need for music discs in Minecraft, because this mod implements only remixes and no copyright sounds.'''
[[dependencies.moredisc]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moredisc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
